export const XAI_COST_MAP = {
    'xai:grok-beta:prompt_tokens': 500,
    'xai:grok-beta:completion-tokens': 1500,
    'xai:grok-vision-beta:prompt_tokens': 500,
    'xai:grok-vision-beta:completion-tokens': 1500,
    'xai:grok-vision-beta:image': 1000,
    'xai:grok-3:prompt_tokens': 300,
    'xai:grok-3:completion-tokens': 1500,
    'xai:grok-3-fast:prompt_tokens': 500,
    'xai:grok-3-fast:completion-tokens': 2500,
    'xai:grok-3-mini:prompt_tokens': 30,
    'xai:grok-3-mini:completion-tokens': 50,
    'xai:grok-3-mini-fast:prompt_tokens': 60,
    'xai:grok-3-mini-fast:completion-tokens': 400,
    'xai:grok-2-vision:prompt_tokens': 200,
    'xai:grok-2-vision:completion-tokens': 1000,
    'xai:grok-2:prompt_tokens': 200,
    'xai:grok-2:completion-tokens': 1000,
    'xai:grok-2-image:output': 7_000_000,
};
//# sourceMappingURL=xaiCostMap.js.map